// <auto-generated />
using System;
using GoalsApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoalsApp.Api.Data.Migrations
{
    [DbContext(typeof(GoalsDbContext))]
    [Migration("20260930155905_AddGoals")]
    partial class AddGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("goals")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoalsApp.Api.Data.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_style");

                    b.Property<bool?>("EnumOrdered")
                        .HasColumnType("boolean")
                        .HasColumnName("enum_ordered");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NumberUnit")
                        .HasColumnType("text")
                        .HasColumnName("number_unit");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("RangeMax")
                        .HasColumnType("integer")
                        .HasColumnName("range_max");

                    b.Property<string>("RangeMaxLabel")
                        .HasColumnType("text")
                        .HasColumnName("range_max_label");

                    b.Property<int?>("RangeMin")
                        .HasColumnType("integer")
                        .HasColumnName("range_min");

                    b.Property<string>("RangeMinLabel")
                        .HasColumnType("text")
                        .HasColumnName("range_min_label");

                    b.Property<string>("TargetComparison")
                        .HasColumnType("text")
                        .HasColumnName("target_comparison");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("numeric")
                        .HasColumnName("target_value");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Position")
                        .HasDatabaseName("ix_goals_user_id_position");

                    b.ToTable("goals", "goals", t =>
                        {
                            t.HasCheckConstraint("ck_goals_display_style", "display_style IN ('toggle', 'input', 'options', 'slider', 'dial', 'buttons', 'stepper', 'emoji_scale')");

                            t.HasCheckConstraint("ck_goals_enum", "(type = 'enum') = (enum_ordered IS NOT NULL)");

                            t.HasCheckConstraint("ck_goals_number", "type = 'number' OR number_unit IS NULL");

                            t.HasCheckConstraint("ck_goals_range", "(type = 'range') = (range_min IS NOT NULL AND range_max IS NOT NULL) AND (range_min IS NULL OR range_min < range_max) AND (type = 'range' OR (range_min_label IS NULL AND range_max_label IS NULL))");

                            t.HasCheckConstraint("ck_goals_target", "(target_comparison IS NULL) = (target_value IS NULL) AND (target_comparison IS NULL OR (type IN ('range', 'number') AND target_comparison IN ('at_least', 'at_most')))");

                            t.HasCheckConstraint("ck_goals_type", "type IN ('boolean', 'range', 'number', 'enum')");
                        });
                });

            modelBuilder.Entity("GoalsApp.Api.Data.Entities.GoalEnumOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("boolean")
                        .HasColumnName("is_target");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ux_goal_enum_options_goal_id_label");

                    b.ToTable("goal_enum_options", "goals");
                });

            modelBuilder.Entity("GoalsApp.Api.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("week_start");

                    b.HasKey("UserId");

                    b.ToTable("profiles", "goals", t =>
                        {
                            t.HasCheckConstraint("ck_profiles_week_start", "week_start IN ('sunday', 'monday')");
                        });
                });

            modelBuilder.Entity("GoalsApp.Api.Data.Entities.GoalEnumOption", b =>
                {
                    b.HasOne("GoalsApp.Api.Data.Entities.Goal", null)
                        .WithMany("Options")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoalsApp.Api.Data.Entities.Goal", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
